[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

# Formatter
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# Testing
[fuzz]
runs = 256
max_test_rejects = 65536

# Networks
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "https://mainnet.base.org"
localhost = "http://127.0.0.1:8545"

# Etherscan Verification
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
